/**
 * SatNOGS bundled data utilities.
 * Data is generated by scripts/generate-satfreq.ts and bundled at build time.
 */

import rawData from './satnogs.json';

// ─── Types ──────────────────────────────────────────────────────

/** Satellite metadata decoded from the compact bundled format. */
export interface SatnogsSatellite {
  name: string | null;
  satId: string;
  names: string | null;
  status: string | null;
  launched: string | null;
  countries: string | null;
  operator: string | null;
  image: string | null;
  website: string | null;
}

/** Transmitter entry decoded from the compact bundled format. */
export interface SatnogsTransmitter {
  description: string;
  frequencyHz: number;
  mode: string | null;
  service: string | null;
}

export interface SatnogsEntry {
  satellite: SatnogsSatellite | null;
  transmitters: SatnogsTransmitter[];
}

/** Lightweight entry for search results. */
export interface SatnogsSearchEntry {
  noradId: number;
  name: string;
  status: string | null;
  services: string[];
  bands: string[];
}

// ─── Data access ────────────────────────────────────────────────

type RawEntry = {
  sat?: (string | null)[];
  tx: (string | number | null)[][];
};

const data = rawData as Record<string, RawEntry>;

function decodeSatellite(raw: (string | null)[]): SatnogsSatellite {
  return {
    name: raw[0] as string | null,
    satId: raw[1] as string,
    names: raw[2] as string | null,
    status: raw[3] as string | null,
    launched: raw[4] as string | null,
    countries: raw[5] as string | null,
    operator: raw[6] as string | null,
    image: raw[7] as string | null,
    website: raw[8] as string | null,
  };
}

function decodeEntry(raw: RawEntry): SatnogsEntry {
  const satellite = raw.sat ? decodeSatellite(raw.sat) : null;

  const transmitters = raw.tx.map(t => ({
    description: t[0] as string,
    frequencyHz: t[1] as number,
    mode: t[2] as string | null,
    service: t[3] as string | null,
  }));

  return { satellite, transmitters };
}

/** Look up SatNOGS data for a satellite by NORAD ID. Returns null if not in database. */
export function getSatnogsData(noradId: number): SatnogsEntry | null {
  const raw = data[String(noradId)];
  if (!raw) return null;
  return decodeEntry(raw);
}

/** Get just the transmitter list for a satellite (for Doppler prefill). */
export function getTransmitters(noradId: number): SatnogsTransmitter[] {
  const raw = data[String(noradId)];
  if (!raw) return [];
  return raw.tx.map(t => ({
    description: t[0] as string,
    frequencyHz: t[1] as number,
    mode: t[2] as string | null,
    service: t[3] as string | null,
  }));
}

/** Check if a satellite has any SatNOGS data. */
export function hasSatnogsData(noradId: number): boolean {
  return String(noradId) in data;
}

// ─── Band classification ────────────────────────────────────────

/** Classify frequency (Hz) into standard radio band letter designation. */
export function freqBand(hz: number): string {
  if (hz < 30e6) return 'HF';
  if (hz < 300e6) return 'VHF';
  if (hz < 1e9) return 'UHF';
  if (hz < 2e9) return 'L';
  if (hz < 4e9) return 'S';
  if (hz < 8e9) return 'C';
  if (hz < 12e9) return 'X';
  if (hz < 18e9) return 'Ku';
  if (hz < 40e9) return 'Ka';
  return 'EHF';
}

// ─── Search index ───────────────────────────────────────────────

let _searchIndex: SatnogsSearchEntry[] | null = null;

/** Get a list of all satellites in the SatNOGS database (for search). Built lazily. */
export function getSatnogsSearchIndex(): SatnogsSearchEntry[] {
  if (_searchIndex) return _searchIndex;
  _searchIndex = [];
  for (const [id, raw] of Object.entries(data)) {
    const noradId = Number(id);
    const name = (raw.sat?.[0] as string | null) ?? `NORAD ${id}`;
    const status = raw.sat?.[3] as string | null;
    const serviceSet = new Set<string>();
    const bandSet = new Set<string>();
    for (const t of raw.tx) {
      const svc = t[3] as string | null;
      if (svc) serviceSet.add(svc);
      const hz = t[1] as number;
      if (hz > 0) bandSet.add(freqBand(hz));
    }
    _searchIndex.push({
      noradId, name, status,
      services: [...serviceSet],
      bands: [...bandSet],
    });
  }
  _searchIndex.sort((a, b) => a.name.localeCompare(b.name));
  return _searchIndex;
}

/** Get set of NORAD IDs that have transmitters in the given frequency range (Hz). */
export function getSatellitesByFreqRange(minHz: number, maxHz: number): Set<number> {
  const result = new Set<number>();
  for (const [id, raw] of Object.entries(data)) {
    for (const t of raw.tx) {
      const hz = t[1] as number;
      if (hz >= minHz && hz <= maxHz) {
        result.add(Number(id));
        break;
      }
    }
  }
  return result;
}

// ─── Display helpers ────────────────────────────────────────────

/** Full URL for a SatNOGS satellite image. */
export function satnogsImageUrl(relativePath: string): string {
  return `https://db.satnogs.org/media/${relativePath}`;
}

/** URL to the SatNOGS satellite detail page. */
export function satnogsPageUrl(satId: string): string {
  return `https://db.satnogs.org/satellite/${satId}/`;
}

// Re-export frequency formatters from shared utility
export { formatFreqHz, formatMHz } from '../format';
